version: "3.1"

services:
  server: &shared
    build:
      context: ./server
      args:
        - NODE_ENV=development
    command: npm run dev
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./server/:/app:cached
      - server_node_modules:/app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DB: starterapp
      DB_USER: starterapp
      DB_PASS: mypassword
      HOSTNAME: localhost
      PORT: 80
      LOG_SQL: "true"
      LOG_LEVEL: debug

  db:
    image: postgres:12.6
    environment:
      - POSTGRES_DB=starterapp
      - POSTGRES_USER=starterapp
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - psql:/var/lib/postgres:delegated

  # redis:
  #   image: redis
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./.redis:/data

  # localstack:
  #   image: localstack/localstack

  # mailcatcher:
  #   image: yappabe/mailcatcher
  #   ports:
  #     - 1025:1025
  #     - 1080:1080

volumes:
  psql:
  server_node_modules:
